
name: 'Unit Test'

on: [ push, pull_request ]

jobs:

  unit-test:
    name: PHP Unit Tests
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        php:
          - '8.2'
          - '8.3'
        typo3:
          - '13.4'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Test on PHP ${{ matrix.php }} on TYPO3 ${{ matrix.typo3 }}
        run: |
          composer remove --dev typo3/cms-form
          composer remove typo3/cms-core typo3/cms-extbase typo3/cms-install
          composer require "typo3/cms-core:^${{ matrix.typo3 }}" "typo3/cms-extbase:^${{ matrix.typo3 }}" "typo3/cms-install:^${{ matrix.typo3 }}"
          composer require --dev "typo3/cms-form:^${{ matrix.typo3 }}"
          make unit
